OS	= $(shell uname -s)
ifeq ($(OS),Linux)
	CURRENT_PATH = $(shell pwd)
endif
ifeq ($(OS),Darwin)
	CURRENT_PATH = ${PWD}
endif

FRONT_NAME = eurovision-back
PORT = 9000

DOCKER_CMD = docker run --rm -it
DOCKER_APP_V = -v ${CURRENT_PATH}/:/app -w /app
DOCKER_IMG_BACK = node:current-alpine3.16

run_release:
	docker run -d --restart=always --name ${FRONT_NAME} -p ${PORT}:${PORT} ${DOCKER_APP_V} --entrypoint=node ${DOCKER_IMG_BACK} index.js

remove:
	docker rm -f ${FRONT_NAME}
